[package]
name = "m3u8-checker"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12"
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.47", features = ["full"] }
anyhow = "1.0.98"
